### ISSUE TITLE
Pathfinding broke, saying it went out of bounds while in the middle of the map

### ISSUE THREAD

**Issue by jamiefp17** [arcturus125/Agile-Assessment#15]
![image](https://user-images.githubusercontent.com/57445543/112223589-0f653600-8c22-11eb-8da0-a5da3aa9d237.png)

**Comment by arcturus125** [comment]
I can't be 100% sure since I haven't tested it. but I believe it may have something to do with the Tile bug I found earlier.

Perhaps try changing to Tile.Vector3ToTile() as directly accessing the tilemap is not recommended

**Comment by arcturus125** [comment]
haven't run into this issue in 2 weeks. i believe i found and fixed the issue in recent commits.
if we run into this issue again, just re-open this issue, do not create another
