### ISSUE TITLE
Shooting has strange aiming irregularities

### ISSUE THREAD

**Issue by jamiefp17** [arcturus125/Agile-Assessment#20]
https://www.mediafire.com/file/0g6bzq8xlott2s7/Desktop+2021.03.27+-+22.24.04.01.mp4/file

**Comment by jamiefp17** [comment]
@arcturus125 test

**Comment by arcturus125** [comment]
I believe that this has something to do with the player and the player's sprite actually being in separate locations.
try to create an empty game object as a child of the player and give it a slight offset on the Z-axis so it is in the middle of the player's sprite (from the camera's view)
then go into the projectile shooting code and change it so the projectile spawn point is the transform of the new game object you just created
