### ISSUE TITLE
different ores look the same

### ISSUE THREAD

**Issue by arcturus125** [arcturus125/Agile-Assessment#30]
currently, all the ores are using the same texture that is rendered over the ground, this means that the player cannot distinguish between the different ores on the floor.

multiple different textures are required to help the player clearly see differences between each ore

@jamiefp17 I was hoping you could tackle this?

**Comment by jamiefp17** [comment]
I've added a note of this on the Kanban board, and it's on my todo list.

**Comment by arcturus125** [comment]
@jamiefp17 when you create your pull request put "closes 30" in the description at the top. it will automatically close this issue when your pull request is merged
